[package]
name = "fiordland"
version = "0.1.0"
authors = ["Aron Widforss <aron@antarkt.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
nom = "5.0.1"
nom_locate = "1.0.0"
