DROP SCHEMA IF EXISTS interface CASCADE;
DROP SCHEMA IF EXISTS phone CASCADE;
DROP SCHEMA IF EXISTS hike CASCADE;

CREATE SCHEMA IF NOT EXISTS interface;
CREATE SCHEMA IF NOT EXISTS phone;
CREATE SCHEMA IF NOT EXISTS hike;
CREATE SCHEMA IF NOT EXISTS uuid;

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA uuid;
